### ISSUE TITLE
Error thrown with quick interactions

### ISSUE THREAD

**Issue by m1212e** [isaacHagoel/svelte-dnd-action#262] opened 2021-03-27 16:09 UTC
When I double click a draggable object I get this error:

`pointerAction.js:180 Uncaught TypeError: Cannot read property 'items' of undefined
    at HTMLElement.handleDraggedLeft (pointerAction.js:180)
    at dispatchDraggedElementLeftContainerForNone (dispatcher.js:69)
    at andNow (observer.js:81)`

**Comment by isaacHagoel** [comment] 2021-03-27 18:09
Can you reproduce it in the REPL and send a link?

**Comment by m1212e** [comment] 2021-03-27 19:42
It actually is reproduceable in the REPL in the Git Readme. I get this after some trying:
`Error:
message: "Cannot read property 'items' of undefined"
stack: TypeError: Cannot read property 'items' of undefined
at HTMLElement.handleDraggedLeft (eval at handle_message (about:srcdoc:13:8), <anonymous>:1628:67)
at dispatchDraggedElementLeftContainerForNone (eval at handle_message (about:srcdoc:13:8), <anonymous>:709:21)
at andNow (eval at handle_message (about:srcdoc:13:8), <anonymous>:1229:17)`

So what I do is, I pick an element and then keep clicking the left mouse button which starts dragging. Then I slightly move the mouse so I always start dragging a little bit. In most cases there is no error on the official REPL but sometimes it works and throws an error. I can't really identify any reason or pattern behind the error. In my particular setup it just gets triggered a lot more often.

**Comment by isaacHagoel** [comment] 2021-03-27 20:29
i tried reproducing with no success. can u provide more details?
which browser?
which OS?
which REPL on the readme?
which list on that REPL?
which element on that list (if it matters)?
are u rapidly clicking all the way through the interaction?

**Comment by m1212e** [comment] 2021-03-27 21:22
1. Brave
2. Win 10
3. https://svelte.dev/repl/e2ef044af75c4b16b424b8219fb31fd9?version=3.22.2
4. Happens on multiple ones
5. I don't think so.
6. Yes, probably

I made a short screencapture, hopefully you'll have better understanding of what I do. With every drag I do with the mouse, I do a doubleclick.
https://user-images.githubusercontent.com/14091540/112735176-b57aae00-8f4a-11eb-8580-3c42a03e53fd.mp4

**Comment by isaacHagoel** [comment] 2021-03-27 21:32
Thanks. Looks exactly like what i tried. Does it reproduce for you on
chrome or only on brave?

**Comment by m1212e** [comment] 2021-03-27 21:47
Also on a fresh installation of Chrome (no addons, nothing):
`Error:
message: "Cannot read property 'items' of undefined"
stack: TypeError: Cannot read property 'items' of undefined
at HTMLElement.handleDraggedLeft (eval at handle_message (about:srcdoc:13:8), <anonymous>:1628:67)
at dispatchDraggedElementLeftContainerForNone (eval at handle_message (about:srcdoc:13:8), <anonymous>:709:21)
at andNow (eval at handle_message (about:srcdoc:13:8), <anonymous>:1229:17)`

In my setup the error is way easier to reproduce, i could host it somewhere and then you could take a look at it, if you want?

**Comment by isaacHagoel** [comment] 2021-03-28 02:58
alright. i was finally able to reproduce it but only on firefox.
on Chrome no matter what I do I can't cause it to happen (even on your app).
I will have a look into it today or tomorrow.

**Comment by isaacHagoel** [comment] 2021-03-28 03:34
Looks like under rapid fire the drag left handler can fire before the drag start handler. I have a one liner fix for it.
Can you try out this branch `262-drag-left-before-start` (I also created a draft MR #264 ) and let me know if it solves the issue for you?

**Comment by m1212e** [comment] 2021-03-28 10:54
It does! Thanks for taking the time and this amazing tool!

**Comment by isaacHagoel** [comment] 2021-03-28 11:08
happy to hear that. reopening the issue so i can close it after this gets released (will do it now)

**Closed** 2021-03-28 11:14 UTC
Labels: bug

**Comment by isaacHagoel** [comment] 2021-03-28 11:16
alright. version 0.9.2 should be available with the fix
