### ISSUE TITLE
Dragging should consider mouse position instead of element center

### ISSUE THREAD

**Issue by fbinz** [isaacHagoel/svelte-dnd-action#248] opened 2021-02-11 10:12 UTC
As it is now, it seems that the center of a dragged element is considered when calculating its "wouldBeIndex" inside a container.
However, when you compare that behavior to other implementations (esp. Trello), they use the current mouse position to decide where the dragged element should appear in the container. I find this much more intuitive.

Would it be possible to include this behavior in svelte-dnd-action?
It seems to me, that `listUtil.findWouldBeIndex` would need to get the current mouse position instead of/in addition to the dragged element (`floatingAboveEl`).

What's your take on this? Should I try to implement this and issue a pull request? Or do you maybe know a quick workaround?

**Comment by isaacHagoel** [comment] 2021-02-11 10:32
There are strong drawbacks to using the mouse position. There is a blog
post from the author of react-beautiful-dnd explaining some.
With that said, i agree that in some cases, it is better.
There is a feature in discussion (in one of the pending PRs), which would
basically be a new option that makes the dragged element position itself
such that its center and is on the mouse pointer on drag start. This should
achieve the best of both worlds, i think.
Thoughts?

**Comment by fbinz** [comment] 2021-02-11 11:24
(Just for reference, I guess you are referring to this blog post: [Link](https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b)/Knowing when to move)

Now to the question:
Thinking about it more, I guess it might depend on the use case.

So, I currently want to implement an app with a trello-like board interface. Starting from your example, I got pretty good results already, but have actually two issues. I prepared a REPL, so you can follow what I mean: [Link](https://svelte.dev/repl/721a40845a2844aa8454124193d045ef?version=3.22.2)

The issues are:

1. When dragging a large element, I would prefer if the other elements "moved out of the way". I guess this needs a different algorithm to determine the placeholder index. Maybe we could look at the space above/below the dragged element to see if the the other elements of the container have enough space to move there.
![issue1](https://user-images.githubusercontent.com/1530332/107629880-06686880-6c63-11eb-8d06-af687a9af390.gif)

2. When dragging to another column, the drop area is actually quite small. The user now has to know that she needs to place the center of the element above the drop area. I guess this issue would be solved by using the mouse position rather than the items center. Repositioning the dragged element so that its center is on the mouse on drag start would also resolve this issue, but might look a bit awkward.
![issue2](https://user-images.githubusercontent.com/1530332/107630205-82fb4700-6c63-11eb-9ddd-5397cd3a6e47.gif)

**Comment by isaacHagoel** [comment] 2021-02-11 21:11
Hi,
thanks for taking the time to take the screen captures.
1. what you are asking for was the original behaviour of the library (u can try an older version), but there were a bunch of issues with it, for example #211 . You can try it yourself by downgrading the lib version to <0.7.4. The current implementation behaves predictably and consistently - the center of the item needs to be above where the item would be if it was in that position in the list. 
2. Notice that in your screen capture your mouse pointer is not above the list at all. Are you asking for the edge of the item to be the focal point in this case? I think that this example is quite contrived. It is easy to solve it by setting some min height on the columns. I am not sure the library should compensate for any kind of not-so-great design choice.

**Comment by isaacHagoel** [comment] 2021-02-12 09:31
please try out the following branch: `249-dragged-jump-to-cursor-on-start` to see how it feels when the dragged element positions itself on the cursor. Currently (at the time of writing this) in this branch it always does it. Still need to make it optional.
See also #250

**Comment by fbinz** [comment] 2021-02-12 09:59
Hi, so I looked at it some more.

Note: Just saw your comment regarding the new branch and tried it. It's definitely nicer for some use-cases, but doesn't solve the "issue". Just as a side note, I think your library is quite awesome and just want to make it even better. :)

Regarding 1:
This is closer to the way that I want the list items to behave, but not quite there. On further investigation, I think that Trello get this "wrong" too. Have a look:
![issue5](https://user-images.githubusercontent.com/1530332/107750545-78e94f00-6d1c-11eb-90bf-66b9a1b8cf31.gif)
The behavior depends on where you grab the card, while I think it should always look consistently the same. This can of course be achieved by using the center of the element, but I'm not a 100% happy with that either.
Maybe I can come up with my own implementation here and share it, if it reaches any level of usability. :)

Regarding 2:
Yes, you're right. I guess what I was trying to reproduce here, was the "trello" behaviour when switching columns:
![issue4](https://user-images.githubusercontent.com/1530332/107751017-1cd2fa80-6d1d-11eb-8afb-26ab6c4d61e7.gif)
This seems to be an unrelated issue, though, because the problem is not the dragging behaviour but more the size of the dropzone. In the trello example, the whole space below the actual rendered part of the list is a dropzone. 
Maybe I'm missing something, but could this even be implemented with the current design?

**Comment by isaacHagoel** [comment] 2021-02-12 10:30
Hi,
1. If you come up with a solution you think is better, please do share.
2. Trello can make many assumptions that this library can't and doesn't want to make. For example: the layout of each column (vertical list) and the layout of the columns relative to one another. 
The library does have a "proximity based" "would be index" detection, but it doesn't apply it in cases like this. We could add such behaviour (always add the dragged element to the nearest dropzone instead of putting it in the origin zone when it is not inside any other zone). It **might** even be possible to achieve this behaviour with some smart html and styling but it doesn't pop into my mind in full details atm (maybe because i'm too tired 🥱 ). The dndzone will have to occupy the full height and all the elements will be surrounded by this dynamically sized grey background (which might need to be position: fixed so it is not a direct child of the dropzone)

**Comment by mataslib** [comment] 2021-02-19 15:21
Hello, first of all, thanks for this amazing easy to use library.  

Problem I see with center position is, that there are "edge" cases when dnd become "useless". These are literaly "edge", because they caused by computer screen edge, which won't let mouse any further. This happens when you have zone positioned at top and there is tall item in zone. Please, see gif bellow:

<details>
  <summary>See gif</summary>
  ![2021-02-19-16-13-45](https://user-images.githubusercontent.com/5154014/108523475-3dc3be80-72ce-11eb-8434-c271700bd00e.gif)
</details>

**Comment by isaacHagoel** [comment] 2021-02-19 19:18
@mataslib why wouldn't the suggested change (elemnt positions its center on the cursor) solve it?

**Comment by mataslib** [comment] 2021-02-19 20:24
@isaacHagoel I just tested it and id does solve it, thanks. However, it feels kind of unnatural  (In my opinion), when item is big and there's handle at top right corner. You start dragging by handle, but item morphs to center, so you're not dragging with handle anymore.

I looked at react-beatiful-dnd how it behaves (since you've mentioned it), they apparently use center too, but center of target item, not dragged one, which solves the issue when center is used.

**Comment by isaacHagoel** [comment] 2021-02-19 20:49
If this feature is added it will be activated using an option. It is not
suitable for the drag handles usecase.
There has to be one point on the dragged element that is checked. It cannot
be on the item below because that allows for ambiguity. For example, a
large item can be above the centers of multipe items below it.

**Comment by isaacHagoel** [comment] 2021-03-28 11:25
I ended up merging this feature in a while ago. I am open to any suggestions for improvements if you have such. 
closing this issue for now.

**Closed by isaacHagoel** 2021-03-28 11:25 UTC
Labels: enhancement
