### ISSUE TITLE
Visual Duplicate Issue (Workaround) && Making a DnD zone compatible with two DnD zones with X and Y types, respectively (Solved)

### ISSUE THREAD

**Issue by LiddellHunter** [isaacHagoel/svelte-dnd-action#483] opened 2023-09-01 20:59 UTC
My project consists of containers and elements and utilizes this DnD library. There is a main dropzone (for containers) that only allows containers and then in each container component there is another DnD zone for elements. There was a duplicate issue happening when dragging an element out of a container and hovering it over the containers dropzone. 

When the element is hovered over the containers dropzone, a copy of the element would snap back to the container while the user is still dragging another copy. My assumption was that the library was trying to drop the element into that DnD and so the consider event would stop firing for the container DnD and the main DnD consider would then fire. 

To attempt to solve this I added types to the DnD zones making them not able ot drop into eachother. This solved a part of my problem. I then couldn't drop either of these objects into another DnD zone marked as the trashcan. 

My fix around this was to remove the typing from the dropzones so they are all of default type and allowed to be dropped into each other then disable the opposite dropzone depending on what object I'm currently dragging. This solved my issue! 

Unfortunately I'm getting a duplicate issue again where dragging a container causes a visual copy of the container to remain in the place I'm dragging from all the while I'm dragging the original around. I've checked the list upon dragging and there is only one copy in the list. Not sure what to do at this point, but I do have a lot of events firing and transferring data around my UI so I think it has to do with the order of how I'm firing some of these events.

**Comment by LiddellHunter** [comment] 2023-09-01 21:00
Also forgot to mention that when dragging the duplicated container around, the visual copy disappears after the consider event is fired while i'm dragging.

**Comment by LiddellHunter** [comment] 2023-09-01 21:09
Possible fix:
I found a fix for the duplicate issue in my case. When disabling the dropzone on a containers inner (elements) dropzone, the container is visually duplicated. Not entirely sure how disabling the dropzone inside of the container causes it to duplicate, but not disabling it fixes my issue.

**Comment by LiddellHunter** [comment] 2023-09-03 00:20
Completely solved: 
There was an issue with having nested dropzones and I'm not sure why. I ended up dispatching events to set the Trash's dropzone's type to whatever component I'm dragging in that moment. This works great, but feels unnecessary. I spent a few too many hours trying other ways and this was my solution.

**Comment by isaacHagoel** [comment] 2023-09-03 10:32
Sorry I haven't been responsive. Super busy couple of days. I will go over this and the other issues tomorrow. Is there a REPL that reproduces the problems you're facing?

**Comment by LiddellHunter** [comment] 2023-09-03 19:58
No worries about not getting to this right away as it's not an emergency.

As for the REPL I can try my best to duplicate the issue in there.  

Before anything, I feel like a simple fix to my issue is to add the dndzone type as a string or array of strings, but I will let you come to that conclusion since you understand your code better than myself.

**Comment by LiddellHunter** [comment] 2023-09-03 21:31
Here is my REPL for the issue: https://svelte.dev/repl/c08096c307d04fe7812e01acc30ed288?version=4.2.0

This is specifically for the duplicating issue.

**Comment by isaacHagoel** [comment] 2023-09-04 11:09
Thanks! the info and REPL are super helpful. I spent time looking into it today and pinpointed the problem (there are conditionals that should be false but are for some reason triggering). I blocked time tomorrow to continue the investigation. Not expecting a response, just FYI. Will keep updating here.

**Comment by isaacHagoel** [comment] 2023-09-05 00:55
I found the issue and fixed it. It should actually help in many nested scenario because this issue exposed an incorrect behaviour of the lib - observing zones within the shadow element. 
I need to thoroughly test it before I can merge since I removed something that was supposed to support Dragula usecases (I tested quickly and it seems to be fine but need to be certain) plus need to test nesting scenarios etc.
I will block more time for it. In the meanwhile you can try out the branch.

**Comment by isaacHagoel** [comment] 2023-09-05 10:29
So actually even though my fix works for this specific case, there is something more vicious in action under the hood. 
It turns out that Svelte inits actions in the opposite order to the rendering order. In other words it inits actions in nested elements before the action in the parent element. 
I created [this simple REPL](https://svelte.dev/repl/4d397dc6f4ac49a0a99b3e36cee7af27?version=4.2.0) to test/prove it.
This is unfortunate from the libs perspective before zones nested in shadow elements inits before their patent is marked as shadow. 
I will keep investigating and hopefully come up with a smart way to prevent these shadow zones from being created in the first place, but Svelte doesn't make make life easy here.

**Comment by LiddellHunter** [comment] 2023-09-05 19:19
Great to know! I'm glad you've managed to uncover some issues (for better or worse) as well. Feel free to keep this thread updated as I'd be happy to know what's happening. It's all a learning experience.

**Comment by isaacHagoel** [comment] 2023-09-06 09:39
I found a solution to the root issue that I am pretty happy with. I have a basic version working, need to clean it up and test, which will hopefully happen tomorrow.

**Comment by geoffkendall** [comment] 2023-09-06 16:38
I've been having a similar issue, so looking forward to a fix. But the main reason for this comment is to thank you Isaac for such a fantastic library — you've saved me DAYS of work. :-)
All the best,
Geoff

**Comment by isaacHagoel** [comment] 2023-09-08 10:45
The linked PR (#488) should be good to go.
I am planning to do a final review tomorrow and merge.
Feel free to try it out and let me know if it solved your problem (it should work out of the box without the new optional hint attribute).

**Closed** 2023-09-09 04:42 UTC
Labels: bug
