### ISSUE TITLE
Board + css scroll snap

### ISSUE THREAD

**Issue by thousandsofraccoons** [isaacHagoel/svelte-dnd-action#252] opened 2021-02-27 04:29 UTC
Board style with scroll snap has some weird behavior during column drag. I tried to turn off scroll snap `on drag start`, but the behavior still there. It scrolls right a little and the left column jumps out of the screen on each drag.

**Comment by isaacHagoel** [comment] 2021-02-27 04:39
REPL please

**Comment by isaacHagoel** [comment] 2021-03-28 11:23
closing this for now. happy to look into this if you provide steps to reproduce (ideally a REPL). if you are interested feel free to re-open

**Comment by thousandsofraccoons** [comment] 2021-04-12 02:09
@isaacHagoel I've done the repl: https://svelte.dev/repl/8ddb027a9f1649dfb68bf82e6887ad42?version=3.22.2 

Please try to horisontally scroll and drag elements from left to right

**Comment by isaacHagoel** [comment] 2021-04-13 23:45
Just to confirm: is the problem you are seeing is that when u drag the column next to the edge of the screen it scrolls rapidly instead of gradually (like it would without scroll snap point)?

**Comment by thousandsofraccoons** [comment] 2021-04-14 14:20
@isaacHagoel yes. At first, I thought that adding `scroll-snap-type: none;` onConsider stage could help, but no luck so far.

**Comment by isaacHagoel** [comment] 2021-04-17 03:45
does this work for you? i made a tiny change.
https://svelte.dev/repl/eed36fe30a33425daf6269d52587dd31?version=3.22.2
I changed the class add/remove logic to leverage svelte and added the option: `centreDraggedOnCursor` to make it consistently easy to make the column scroll the container.

**Comment by isaacHagoel** [comment] 2021-04-26 01:09
@thousandsofraccoons following up. have u looked at the solution above?

**Comment by thousandsofraccoons** [comment] 2021-05-05 03:37
@isaacHagoel it doesn't. Please, try to reproduce - scroll to 3rd card right, then move this card right.

**Comment by isaacHagoel** [comment] 2021-05-05 04:41
@thousandsofraccoons seems to me like it's working but maybe my expectations are incorrect. more info pls

**Comment by isaacHagoel** [comment] 2021-11-17 12:00
since it seems to me that my fix solved the problem and i haven't heard back I am closing this one for now

**Closed by isaacHagoel** 2021-11-17 12:00 UTC
