### ISSUE TITLE
Jittering when the list items use Quill

### ISSUE THREAD

**Issue by jelliedpizza** [isaacHagoel/svelte-dnd-action#507] opened 2023-10-27 23:13 UTC
Is there any way to make it work elements that can change in size?

**Comment by isaacHagoel** [comment] 2023-10-27 23:45
What's the issue you are experiencing? Can you include a REPL?

**Comment by jelliedpizza** [comment] 2023-10-28 17:43
I think my issue also may be something else but I'm trying to get this to work without flickering: https://svelte.dev/repl/355a9de05d084208a4c02c1bfd5a1247

**Comment by isaacHagoel** [comment] 2023-10-29 10:36
maybe i am too tired but what is flickering in this REPL?
can you provide exact steps to reprod? i tried dragging the multiline item
and other items.
also, which browser r u using?

**Comment by jelliedpizza** [comment] 2023-10-29 14:12
I'm usually in edge but it look the same in every browser I've tried:
https://github.com/isaacHagoel/svelte-dnd-action/assets/17023013/416fcd6c-d009-45a1-8c35-ae884757e246

**Comment by fnimick** [comment] 2023-10-29 20:40
I suspect this is happening because the shadow element with no content but the same copied styles (including min-height) set is present in the container for a single frame while its content is removed and the source dropped element is also present. This causes an empty element with min-height to be present, pushing the other container items down, which then immediately snap back up when the shadow element is removed.

**Comment by jelliedpizza** [comment] 2023-10-29 21:17
What solution would be appropriate here? Would I need to create a custom
shadow element?
Also, why doesn't the library simply create the shadow element based on the
height/width of the dragged element? That way you wouldn't have to worry
about having components as draggables etc.

**Comment by isaacHagoel** [comment] 2023-10-29 21:48
Right. I see the issue now.
I don't think min-height is the issue. Try pasting this in a REPL
```html
<style>
	section {
		width: 12em;
		padding: 1em;
	}
	div {
		min-height: 1.5em;
		width: 10em;
		text-align: center;
		border: 1px solid black;
		margin: 0.2em;
		padding: 0.3em;
	}
</style>
<script>
	import {dndzone} from 'svelte-dnd-action';
	import {flip} from 'svelte/animate';
	const flipDurationMs = 100;
	function handleSort(e) {
		items = e.detail.items;
	}
	let items = [
		{id:3, title: 'Yoda 323231323 213231232'},
		{id:1, title: 'I'},
		{id:2, title: 'Am'}
	];
</script>
<section use:dndzone={{items, flipDurationMs}} on:consider={handleSort} on:finalize={handleSort}>
	{#each items as item(item.id)}
		<div animate:flip={{duration:flipDurationMs}}>
			{item.title}	
		</div>
	{/each}
</section>
```

To explain what the lib does:
The shadow element is just whatever svelte renders normally in the list but inline style is added to it in order to hide it.
If it jumps like this it means that for some reason it is rendered with a slightly different height (by svelte/ Quill).
The dragged element is a clone of the original element. It copies its appearance from the shadow element occasionally in order to look consistent with how it would look if dropped. In a single list scenario you could just maintain its original appearance but once there are multiple lists, that potentially render the same data differently this becomes important.
Can you reproduce the issue without Quill?
If not, we should be looking for a potential conflict between the two libs.

**Comment by jelliedpizza** [comment] 2023-10-29 22:00
Works well without quill, what I suspect the issue is right now is that it takes a frame or two for the library to initialize so that is why there is no issue when its one line: the height of the element with/without quill loaded is the same, but as the multi-line shadow element is cloned the height with/without quill is different thus making everything jump. What do you think?

**Comment by isaacHagoel** [comment] 2023-10-29 22:21
Could be. I wonder if Quill itself provides any params or whatever that could help. If not, one option might be to store the height of the list elements (I think Svelte has the ability to bind a variable to the height automatically) and then make it the min-height of the shadow element on drag start. Not sure if it would work

**Comment by jelliedpizza** [comment] 2023-10-29 23:37
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/17023013/8862b95b-41ce-4333-8cd3-d9e36bb65b20)

In this screen shot from my own code, I've modified your library to not apply visibility:hidden to the shadow element and I went frame by frame to find the moment when I start dragging (shoddy debugging haha). As you can see, indeed in this one frame quill is loaded until the next so the element is not the correct height.

So what I don't understand is why does the shadow element need to rerender when it only should turn invisible? Would there be a way to not make it rerender thus having to reload Quill which takes one frame?

**Comment by isaacHagoel** [comment] 2023-10-30 00:32
The shadow element is rendered (and then turned invisible) for two reasons:
1. we need to copy the styles from it to the dragged element to allow
features such as morphing
2. we need the correct amount of space is available in the list so that
there is "room" for the dragged element and svelte controls rendering that
list

**Comment by jelliedpizza** [comment] 2023-10-30 00:39
I understand this. My question was rather about why is it re-rendered?

**Comment by isaacHagoel** [comment] 2023-10-30 01:19
It is re-rendered because its id is replaced with a temporary id for the
duration of the drag.
This was introduced in order to address other issues. See
https://github.com/isaacHagoel/svelte-dnd-action/pull/213/files

**Comment by jelliedpizza** [comment] 2023-10-30 01:45
Wouldn't it be easier simply never removing the original element, just making it invisible so it doesn't even need to be re-rendered or removed or replaced?
Also what do you think I should do make the height of the shadow element constant with the original one so the flickering doesn't happen? Where should I store it?
And I wanted to say you're amazing for maintaining this lib and for answering my stupid questions haha

**Comment by isaacHagoel** [comment] 2023-10-30 02:54
Lol. Your questions are not stupid.
At the beginning the original element stayed in the list without being
re-rendered but as I said - that cause issues (I can try to dig up
additional old issues)
The height cannot be constant in the general case because someone can
decide that different indexes in the same list could render at a different
height (so as the element dragged over a different index it will resize
itself), different lists that the elements can be dragged over can render
it with different height, flipping the screen on mobile can require it to
change its height etc.
What I suggested is just a workaround, I can try it and send a REPL when I
have some time.

**Comment by jelliedpizza** [comment] 2023-10-30 19:59
That makes sense. I'm going to tinker with it for a while but I'm awaiting your REPL. Thanks!

**Comment by isaacHagoel** [comment] 2023-10-30 23:40
Here is what I meant. 
https://svelte.dev/repl/ff298ab4ef9a4072bf6a5e3fbbc3cf2e?version=4.2.2
It still jitters on drop but that can probably be addressed in a similar manner

**Closed** 2023-11-08 03:41 UTC
