### ISSUE TITLE
Items can't be a Svelte Component

### ISSUE THREAD

**Issue by raguay** [isaacHagoel/svelte-dnd-action#80] opened 2020-06-12 08:38 UTC
I originally made it with the items to be moved a Svelte component. It constantly threw errors about not able to set a style flag. Then I wrapped the Svelte component inside of a div and it works fine now. You might want to put this into the documentation.

**Comment by isaacHagoel** [comment] 2020-06-12 09:03
Hi @raguay, thanks for the issue.
I tried to reproduce it in the REPL but couldn't. Find my attempt [here](https://svelte.dev/repl/4e0611397bd74f88ab19c11b9fcc56d2?version=3.23.2).
(Side note: there are no animations in this REPL because 'animate' doesn't support it for svelte components only for DOM elements in a keyed list). 
 
Can you reproduce it for me in a REPL?

**Comment by raguay** [comment] 2020-06-12 09:14
I can't reproduce it in a Repl. But, on my system which is a full Kanban
board implementation for my local use. It will only work when I surround
the component in a local div. Not sure what is wrong with it.

**Comment by isaacHagoel** [comment] 2020-06-12 09:30
What are the exceptions that you are getting?

**Comment by raguay** [comment] 2020-06-12 09:37
Uncaught TypeError: Cannot set property 'userSelect' of undefined
    at styleDraggable (styler.js:83)
    at configure (action.js:290)
    at dndzone (action.js:304)
    at Object.mount [as m] (List.svelte:1)
    at mount_component (index.mjs:1350)
    at Object.mount [as m] (ListContainer.svelte:6)
    at Object.mount [as m] (ListContainer.svelte:3)
    at Object.update [as p] (ListContainer.svelte:2)
    at update (index.mjs:707)
    at flush (index.mjs:676)

**Comment by isaacHagoel** [comment] 2020-06-12 11:39
mmm... I wonder what could make that happen.
If you could provide more details/ code snippets from your App maybe I will be able to figure it out.

**Comment by raguay** [comment] 2020-06-13 08:40
https://github.com/raguay/SvelteKanban

I currently have the `div` elements around the `Item` element in the `List.svelte` file. If you take those divs out, you get the error. With the divs, there isn't an error and drag and drop work fine.

**Comment by isaacHagoel** [comment] 2020-06-14 07:37
I am assuming you are referring to line 20 in List.svelte:
```html
 <div animate:flip="{{duration: flipDurationMs}}">
        <Item itemInfo={item} 
```
right?
Without the surrounding div, where would you place `animate:flip` (afaik you can only put it on DOM elements)?
do you remove it as well?

**Comment by raguay** [comment] 2020-06-14 08:23
I removed all the animation as well. I just have the bare bones for dnd
action to begin. That is when it gave the error I sent before.

**Comment by isaacHagoel** [comment] 2020-06-17 11:09
@raguay I clone your repo, removed the surrounding div and it works fine.
in other words. I can't reproduce. 
Closing this for now. Please let me know if u encounter it again or discover how to reproduce.

**Closed by isaacHagoel** 2020-06-17 11:09 UTC

**Comment by raguay** [comment] 2020-06-18 15:14
Oh. I updated the whole project using 'npm update' and it now works. I must of had an outdated library. Thanks.
