### ISSUE TITLE
styling and unstyling of shaddow item is inconsistent

### ISSUE THREAD

**Issue by janrito** [isaacHagoel/svelte-dnd-action#282] opened 2021-04-27 10:24 UTC
https://svelte.dev/repl/8509d73f57e14a8ab892f56cada5d9b2?version=3.37.0

I've set up two lists where one can move items by dragging. Items will always be attached to the end of the list - via a store. This works fine. 

I'm now trying to add a key modifier (CMD) so that wwhen it is pressed, the item wont be moved from one list to the other, instead, the origninal item would be kept in the first list, and a copy will be added to the second. This also kind of works, but as you can see the original item is not being made visible again after the dragging is done.

Not sure how to fix this behaviour.

**Comment by isaacHagoel** [comment] 2021-04-27 10:50
Hi @janrito your consider and finalize handlers look quite complex. 
I can spend some time on it tomorrow. The issue is not unstyling. The issue is that there is a shadow item at all after drop.
It seems like you are changing the ids dynamically based on the list and the index. Is that so? if it is - this is a big no-no. The id should be the same throughout the entire lifecycle of the item and it should not be based on the index.

**Comment by janrito** [comment] 2021-04-27 11:18
Hi @isaacHagoel thanks for looking into this.

The id gets of the dropped item gets changed only when the store is modified, when the moving is finalised (otherwise you might end up with items with the same id).  Think of this as committing the change to a database.

Throught he whole process there are the stores which keep the canonical list of items per list, and a `tempItems` which includes any possible changes. After the drop is finalised, the items param is reset back to the store. In the case of the list where the item is being coped from, the store is unmodified. In the case of the list where the item is dragged to, the store has a new item (with a new Id)

**Comment by janrito** [comment] 2021-04-27 11:31
This might or might not be part of the problem, but, the `mousedown` `mouseup` and `mousemove` events expose active/inactive modifier keys (`cmdKey` `metaKey` `ctrlKey`). It would be nice if the custom events would forward those as well

**Comment by isaacHagoel** [comment] 2021-04-27 11:37
I don't mind exposing it. we can create a ticket for that.
About the changing ids, can u try allocating a new random one without
modifying the existing items?
For some reason the shadow item gets rendered and the only thing that can
do it is your #each block (the lib does not render any items besides the
dragged element, which is a copy of the original element)

**Comment by janrito** [comment] 2021-04-27 12:04
sorry, it doesn't modify the existing items:
This:
```    
$items = [...$items, { id: `${name}/${$items.length}`, name: droppedItem.name }];
```
adds the dropped item to the store of the dragged to list with a new id (i can change the id to be randomly generated)

And this:
```
if (metaKeyActive) {
      $items = [...$items];
    } else {
      $items = [...$items.filter(item => item.id !== id)];
    }
```
removes the dragged item from the dragged from list if the meta key is not active, or just reassigns the unmofidied items to the store in order to trigger reactivity

**Comment by janrito** [comment] 2021-04-27 12:05
> I don't mind exposing it. we can create a ticket for that.
that would be amazing

**Comment by isaacHagoel** [comment] 2021-04-28 03:24
@janrito 
I looked some more. What happens become apparent when u render the stringified value of `_items`.
When the dragged element leaves the list, the shadow item marker is removed from the shadow item while its id remains the original id. A copy is created only on drop.
This means that the library loses track of this item being a shadow item and both the library and svelte consider it as the same original item rather than a copy (because it has the same id).

If you look at the [copy-on-drag examples that are linked to in the README](https://svelte.dev/repl/924b4cc920524065a637fa910fe10193?version=3.24.1), you will see that copying (plus allocating a new id) needs to happen when drag starts (in your case, when drag starts with "cmd" pressed).

**Comment by janrito** [comment] 2021-04-28 11:08
Right, yes, this works:
https://svelte.dev/repl/8509d73f57e14a8ab892f56cada5d9b2?version=3.37.0

The original list and new list reflect changes after simple dragging and also copy-dragging. The only problem is when the meta key is pressed in flight. If that happens, then we get the same problem as before.

**Comment by isaacHagoel** [comment] 2021-04-28 12:07
what is the expected behaviour when the meta key is pressed in flight?
shouldn't it just be ignored (as most apps do)?

**Comment by janrito** [comment] 2021-04-28 20:52
I've just checked a couple of different apps and realised that the key that I actually mean is not meta, but alt. I've updated that in the repl.

If you drag a file in osx though, it doesn't matter if you start the dragging with alt pressed or press it in flight, the effect is the same: a copy of the file will be made on drop. The same happens if you drag a firefox tab, regardless of whether you press alt before or after you start dragging.

**Comment by janrito** [comment] 2021-04-28 21:13
I guess some of this could be achieved if a `consider` event would be fired when on alt keydown (and up) and the event would expose the key properties

**Comment by isaacHagoel** [comment] 2021-04-28 21:36
Can you listen on the alt key and when it's pressed mid drag make a copy in
the origin zone?

**Comment by janrito** [comment] 2021-04-28 21:44
I can, but that keydown event doesn't have access to the consider event `event.detail.items`

**Comment by janrito** [comment] 2021-04-28 21:45
Also, how do I know which item is being dragged from fhe keydown event?

**Comment by isaacHagoel** [comment] 2021-04-28 21:51
What i mean is you keep all of info you need in order to make the clone
action in some global place that also has the items for all dndzones (ex:
App via callback)
When drag starts without alt you keep the item's data, the id of the origin
zone.

**Comment by janrito** [comment] 2021-04-29 10:09
I'm not sure I understand. In order to achieve what the copy-on-drag example does, the event.detail.items prop is modified in place and it is assigned to the action items. 

I think we might be veering too far away off course though (sorry). I think I better understand how this works. 

The question of exposing the modifier key states to the consider/finalize events is still valid I think. Would that be something you are willing to do? (Happy to help here too)

**Comment by isaacHagoel** [comment] 2021-04-29 10:29
I am willing to do it. sure. happy to get a MR. I didn't think it through
but if it can be added organically to the code (need to consider keyboard
dragging too) then sure, why not.
There is no meaning to modifying e.detail.items in place (I did it this way
out of laziness :)). The source of truth for items is whatever you pass to
the #each block and the library.
You can add a new item to a list mid drag and it should work just fine.
I can create a simple example, if my explanations are too hand-wavy, when I
manage to find some time.

**Comment by isaacHagoel** [comment] 2021-08-03 21:54
I noticed this is still open. Any updates?

**Comment by janrito** [comment] 2021-08-05 08:13
Yeah. Sorry. I used a workaround and haven't had time to come back.

**Comment by isaacHagoel** [comment] 2021-11-17 11:59
closing for now. exposing the original event and the modifier is easy. if anyone needs it, feel free to re-open or create a new issue

**Closed by isaacHagoel** 2021-11-17 11:59 UTC
