### ISSUE TITLE
How to do like a 'copy' dropEffect in this package?

### ISSUE THREAD

**Issue by Miniontoby** [isaacHagoel/svelte-dnd-action#494] opened 2023-09-13 18:49 UTC
Hi,.

How to use this to AND have a sortable list AND to let one of the items be assigned to an container.

WHen using the native drag/drop things, I was using: `e.dataTransfer.dropEffect = 'copy';` but since I am having an app which cannot use the native drag/drop because I also want file drag/drop with full path.

So this package is already perfect for my list, but my list items need to be able to be dropped into an container where they are being shown (like actually render the content of that item).

Just think of it as a gallery, every list item is an image, but it is only the filename. And then you drop the list item into the big container it will show the actual image.

So how would I be able do that? Or can this be added/implemented?

Kind Regards,
- Miniontoby

**Comment by isaacHagoel** [comment] 2023-09-13 20:50
For copying have you seen the 'dragupa' examples in the readme?
For displaying the item as just a name or the content in different
container, sounds straightforward to me. The lib doesn't interfere with
this, you can render the items however you like. I might be
misunderstanding your question.

**Comment by Miniontoby** [comment] 2023-09-14 06:02
Yeah, you didnt understand it....

I want to be able to drop an item showing text but INCLUDING an reference
to an item of my list.

Once i drop an item into one of my big containers, then the full element
must be retreived from an event and then I should be able to get the item
of my list with help of the html element reference.

Then with the full item, i then build up the needed code for the item and i
put that code into the container innerhtml.

The dragupa example is not what i need.



Op woensdag 13 september 2023 schreef Isaac Hagoel ***@***.***
>:

> For copying have you seen the 'dragupa' examples in the readme?
> For displaying the item as just a name or the content in different
> container, sounds straightforward to me. The lib doesn't interfere with
> this, you can render the items however you like. I might be
> misunderstanding your question.
>

**Comment by isaacHagoel** [comment] 2023-09-14 06:22
Mmm I know it is super clear in your mind but it's hard for me to follow.
Can you make a REPL that we can collab on?

**Comment by Miniontoby** [comment] 2023-09-14 08:42
Yo, Here is the repl: https://svelte.dev/repl/9fffc8ef1bb3450a9f85ab9b7033ff7e?version=4.2.0

**Comment by isaacHagoel** [comment] 2023-09-14 10:37
Cool, so the ask is to build this with svelte-dnd-action, correct?
1. You want one list on the left with the items, and they can be reordered
within that list
2. You want two drop containers on the right, which contain the last item
that was dropped there (and display its data in a different way)
3. When lifting an item from the list on the left you want to lift a copy
rather than the original, if the copy is dropped back into the list of the
left nothing happens, if it is dropped to one of the containers all good.
Any requirements I missed?

**Comment by Miniontoby** [comment] 2023-09-14 10:43
1. That's is correct and what `svelte-dnd-action` already does 

2. It is not specifically only 2 drop containers, since it might just be unlimited, but for the demo I used 2... 

3. It is more like `If the copy is dropped back into the list of the left, it will still do the ordering system (and if it is placed on the original position, it will do nothing)`

**Comment by Miniontoby** [comment] 2023-09-14 11:00
It could be possible to use an combination of `dragDisabled` and `transformDraggedElement`, but then I will lose my items...

Because the CURRENT copy feature (from 'dragupa' example) cannot be ONLY 'enabled' for a specific 'target' (A or B slot)... 
Because the list on the left still needs to be reorderable without making copies.

**Comment by isaacHagoel** [comment] 2023-09-14 11:24
I will try to find time to play with it tomorrow

**Comment by isaacHagoel** [comment] 2023-09-15 07:05
> Because the list on the left still needs to be reorderable without making copies.
So what do you imagine the UX to be like? do you want the item on the left list to stand still when the copy hovers above or move and make room for the copy or something else entirely?

**Comment by Miniontoby** [comment] 2023-09-16 08:50
It would be nice if the item on the left would stand still whenever I moved it out of there and hovering above the copy container. It shouldn't go like flickering.

When dropped the item into the container, the original location from the original dropzone should be used for the copy, since it is going to be like a playlist and that shouldn't change order when you just drop an item into one of the drop-one-only containers. (since they should only consist of one item...)

**Comment by isaacHagoel** [comment] 2023-09-16 11:35
Sound like what you need is copy on drop in one of the big containers
rather than on drag start.
That is easily doable but if there is already an item in a container and it
will be replaced when dropping the dragged item there I wonder how that
would work. When the item hovers over it, how would that be shown to the
user?

**Comment by Miniontoby** [comment] 2023-09-18 15:07
Yes, that is correct. "Copy on drop" is what I need.

In my current code, once an item is dropped into the container, javascript code will build the 'matching' html code. (matching as in for the type of the item).

For when the item hovers over my container: It should show some indication of it being a droppable zone.

**Comment by Miniontoby** [comment] 2024-01-27 15:45
Hi,

I am kind of still waiting for you to make it.

I did try it myself, but because of the way I made the items (they are `<li>`'s with a custom 'bullet'), they just get very offset and such. 

So I would really like a better solution

**Comment by isaacHagoel** [comment] 2024-01-27 21:27
Ah sorry, I have this example for copy on drop - does it help?
https://svelte.dev/repl/b4e120c45c3e48e49a0d637f0cf097d9?version=4.2.9

**Comment by Miniontoby** [comment] 2024-02-02 21:14
Thanks for the repl, but it doesn't help me, since mine doesn't seem to allow me to drop if I do not set the items of the drop zone to the one that is considered... 

But yeah, I do not use the dropped item for rendering the content of the item... idk if that might be causing some issues as well...

**Comment by isaacHagoel** [comment] 2024-02-02 22:59
I am happy to help but need you to make a Repl showing where you are stuck
and ideally specifying (in text) the exact actual vs. expected behaviour

**Comment by Miniontoby** [comment] 2024-02-03 11:41
My code is over complicated and has too many features to just put into a repl, but I will try to minimalize it down to the bare bones.

And here is a summary of what my code does.

> It is a text projection software. You can make a playlist by selecting songs, videos, pictures and urls. These will be displayed in the dragdrop box. You can sort them in the order you want to display them for example.
> These playlist items are made out of <li>'s with a custom bullet depending on the type of item. (e.g. paper if song, folder if video/picture and url icon if url)

> Then there are two slots, A and B. And I added dropzones at the same locations, meaning they overlap. You can drag the playlist item into the dropzone and then the slot (not the dropzone) will load itself up with the content of the playlist item (so if it is a song, then it will load the song from a file and then display it. If it is a video or picture or url, it will load as a button to show on screen).

About my issue:

I expected the items to just stay what they are when dragging them out of the dropzone (so keep the custom bullet) and to stay at the mouse cursor.

But what happens is that the custom bullet is replaced by the default one, the delete button is no longer red and most importantly: the element moves to the left of the cursor when entering a slot for the first time and then stays offset. If I then move the item left to right and left to right, and so on, then the element gets very offset and then it loses 'grip' and puts it back into the playlist...

I could make a video showcasing it, but yeah, a repl would be helpful as well...

I will try my best to scale it down

**Comment by Miniontoby** [comment] 2024-02-03 14:41
Oke, so changing the `morphDisabled` to true did fix the offset'ing issue.


(The rest of this comment was made after a while of testing and making my code as small and as basic as possible)

Oke, now after some more time I found out I can just fill the dropzone with an `<div/>` and then it will let me drop without it stopping to work and I seem to be able to remove the `morphDisabled` again...

The only problem I see is that when I drop the item, it does kinda glitch to the top left of the dropzone...

I recorded it, it is at the last few seconds:

https://github.com/isaacHagoel/svelte-dnd-action/assets/47940064/ca1d3c64-aaae-42b6-b8d5-4bc56eea9411

**Comment by isaacHagoel** [comment] 2024-02-03 20:40
In general your code renders the items, the exception is the dragged item and the animation from where it was dropped to its final position (that is determined by your code) which are rendered by the lib.
So this is just a guess but it could be because the lib is trying to [animate the element to its final position](https://github.com/isaacHagoel/svelte-dnd-action/blob/6b180fb58c334a825080f0c937d5fc67842b4995/src/pointerAction.js#L272) and that position is where you see that flash for some reason.
You can test this theory by making this function return right away or not call it (modify in your node_modules). If that's the reason the next step is to debug and see why it thinks that this is the final location.

**Comment by isaacHagoel** [comment] 2024-02-04 16:43
Yes

**Comment by Miniontoby** [comment] 2024-02-04 18:55
That did not fix it...

**Comment by isaacHagoel** [comment] 2024-02-04 19:18
So that's when I ask for a simple repl again

**Comment by Miniontoby** [comment] 2024-02-05 15:08
Here you go:

https://svelte.dev/repl/d2434ffdcbe24f7f9dfa7250777146fd?version=4.2.9

**Comment by isaacHagoel** [comment] 2024-02-06 03:41
I spent some time on this now.. I haven't finished debugging it but let me share what i have found so far.
1. it is the final animation into place as I suspected. If you modify the function in pointerActions like so
```javascript
function animateDraggedToFinalPosition(shadowElIdx, callback) {
    console.warn("nope");
    const me = 1;
    if (me === 1) return callback();
    const shadowElRect = getBoundingRectNoTransforms(shadowElDropZone.children[shadowElIdx]); //this line is already there
   ...
```
It won't flash.
2. When there is no shadow item in the list (I would expect that to be the case here) the lib won't animate, but somehow it see it in index 0 (that's the mystery I will need to look into next time i debug this, i didn't see anything passing any items to that dndzone at any point)
3. Your code violates a bunch of the libs rules, specifically you have no consider handler on the slot and u r not updating the items in the event handlers but that doesn't seem to be the root cause.

**Comment by Miniontoby** [comment] 2024-02-06 15:05
1. I need to be able to inject that code for it to work, since I cannot force stuff like github actions (for cross platform building) to have that code in there.
2. I guess that kinda makes sense
3. I looked at [your repl](https://svelte.dev/repl/b4e120c45c3e48e49a0d637f0cf097d9?version=4.2.9) and then I noticed that the consider handler for the dropzone did not actually do anything. Let me explain: I personally do not need to add opacity, so I removed that part. Then there was this part where it just updated the item with the contents of the item, meaning that is actually also useless, so removed it. This gave me an empty consider function, so I removed the handler.

**Comment by isaacHagoel** [comment] 2024-02-06 22:42
I found out why the lib gets it wrong and sees the shadow element in the zone even though it is not there. Created issue #540

**Comment by isaacHagoel** [comment] 2024-03-21 02:30
This is fixed in version 0.9.42

**Closed by isaacHagoel** 2024-03-21 02:30 UTC

**Comment by Miniontoby** [comment] 2024-03-21 11:53
I have updated to the latest version, but the problem itself still seems to be there, tho...

**Comment by isaacHagoel** [comment] 2024-03-25 10:22
Does it still jump to the corner for you?

**Comment by Miniontoby** [comment] 2024-04-07 16:53
Yes it does still jump!

P.s. sorry for the late response, for some reason gmail didn't put the email into the main inbox...
